### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by FlorianHeigl** [lucascbeyeler/zimbra#19]
one error i saw on multiple tests:

```
TASK [lucascbeyeler.zimbra : Enabling Zimbra's admin through Proxy Server] ******************************************************
task path: /Users/floh/.ansible/roles/lucascbeyeler.zimbra/tasks/configure/proxy.yml:4
[WARNING]: Unable to use /opt/zimbra/.ansible/tmp as temporary directory, failing back to system: [Errno 13] Permission denied:
'/opt/zimbra/.ansible/tmp'
changed: [Zimbra-T] => {"changed": true, "cmd": ["./zmproxyconfig", "-e", "-w", "-C", "-H", "Zimbra-T.florianheigl.me"], "delta": "0:00:07.303162", "end": "2021-04-03 05:11:57.799669", "rc": 0, "start": "2021-04-03 05:11:50.496507", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

**Comment by lucascbeyeler** [comment]
That's a permission problem - your zimbra user is unable to create files inside /opt/zimbra or the file already exists.

**Comment by maxxer** [comment]
That's the default for Zimbra installation. For the same problem I did

```yaml
- name: "Temporary workdir for zimbra commands"
  file:
    path: "{{ workdir + '/ansibletmp' }}"
    owner: zimbra
    group: zimbra
    state: directory

- name: "Flush Zimbra cache"
  ansible.builtin.command: /opt/zimbra/bin/zmprov fc -a zimlet
  become: yes
  become_user: zimbra
  vars:
    ansible_remote_tmp: "{{ workdir + '/ansibletmp' }}"
```
